spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plantcare_db
    username: WZY
    password: Wang123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: DEBUG
